services:
  - type: web
    name: kharandi-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kharandi-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: kharandi-db
    databaseName: kharandi
    user: kharandi_user
    plan: free
